In [6]:
import pandas as pd

In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-1.1.3-cp37-cp37m-manylinux1_x86_64.whl (9.5 MB)
     |████████████████████████████████| 9.5 MB 5.1 MB/s eta 0:00:01     |▋                               | 194 kB 5.1 MB/s eta 0:00:02
Requirement already satisfied: python-dateutil>=2.7.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (2.8.1)
Collecting pytz>=2017.2
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 28.1 MB/s eta 0:00:01
Collecting numpy>=1.15.4
  Downloading numpy-1.19.2-cp37-cp37m-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 19.5 MB/s eta 0:00:01    |███████▍                        | 3.4 MB 19.5 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Installing collected packages: pytz, numpy, pandas
Successfully installed numpy-1.19.2 pandas-1.1.3 pytz-2020.1

In [7]:
caschool = pd.read_stata("caschool.dta")

In [8]:
caschool

,observation_number,dist_cod,county,district,gr_span,enrl_tot,teachers,calw_pct,meal_pct,computer,testscr,comp_stu,expn_stu,str,avginc,el_pct,read_scr,math_scr
0,1.0,75119.0,Alameda,Sunol Glen Unified,KK-08,195.0,10.900000,0.510200,2.040800,67.0,690.799988,0.343590,6384.911133,17.889910,22.690001,0.000000,691.599976,690.000000
1,2.0,61499.0,Butte,Manzanita Elementary,KK-08,240.0,11.150000,15.416700,47.916698,101.0,661.200012,0.420833,5099.380859,21.524664,9.824000,4.583333,660.500000,661.900024
2,3.0,61549.0,Butte,Thermalito Union Elementary,KK-08,1550.0,82.900002,55.032299,76.322601,169.0,643.599976,0.109032,5501.954590,18.697226,8.978000,30.000002,636.299988,650.900024
3,4.0,61457.0,Butte,Golden Feather Union Elementary,KK-08,243.0,14.000000,36.475399,77.049202,85.0,647.700012,0.349794,7101.831055,17.357143,8.978000,0.000000,651.900024,643.500000
4,5.0,61523.0,Butte,Palermo Union Elementary,KK-08,1335.0,71.500000,33.108601,78.427002,171.0,640.849976,0.128090,5235.987793,18.671329,9.080333,13.857677,641.799988,639.900024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,416.0,68957.0,San Mateo,Las Lomitas Elementary,KK-08,984.0,59.730000,0.101600,3.556900,195.0,704.300049,0.198171,7290.338867,16.474134,28.716999,5.995935,700.900024,707.700012
416,417.0,69518.0,Santa Clara,Los Altos Elementary,KK-08,3724.0,208.479996,1.074100,1.503800,721.0,706.750000,0.193609,5741.462891,17.862625,41.734108,4.726101,704.000000,709.500000
417,418.0,72611.0,Ventura,Somis Union Elementary,KK-08,441.0,20.150000,3.563500,37.193802,45.0,645.000000,0.102041,4402.831543,21.885857,23.733000,24.263039,648.299988,641.700012
418,419.0,72744.0,Yuba,Plumas Elementary,KK-08,101.0,5.000000,11.881200,59.405899,14.0,672.200012,0.138614,4776.336426,20.200001,9.952000,2.970297,667.900024,676.500000
419,420.0,72751.0,Yuba,Wheatland Elementary,KK-08,1778.0,93.400002,6.923500,47.571201,313.0,655.750000,0.176041,5993.392578,19.036402,12.502000,5.005624,660.500000,651.000000